package io.github.realmcraft.companion.core;
import java.io.*;
import java.nio.file.*;
import java.security.*;
import java.util.*;
/** Optional disposable cache of decoded, checksum-verified source files. */
public final class TerrainDiskCache {
    private static File root;private static final int MAX=8*1024*1024;public static int hits;
    public static synchronized void configure(File folder)throws IOException{if(!folder.mkdirs()&&!folder.isDirectory())throw new IOException("Cache unavailable");root=folder.getCanonicalFile();}
    private static byte[] hash(byte[] b){try{return MessageDigest.getInstance("SHA-256").digest(b);}catch(Exception e){throw new AssertionError(e);}}
    private static String key(String key){StringBuilder s=new StringBuilder();for(byte b:hash(key.getBytes(java.nio.charset.StandardCharsets.UTF_8)))s.append(String.format(Locale.ROOT,"%02x",b&255));return s.toString();}
    static synchronized ChunkSurface read(String key){if(root==null)return null;File f=new File(root,key(key));try{if(!f.isFile()||f.length()>MAX||!f.getCanonicalFile().equals(f.getAbsoluteFile()))return null;byte[] all=Files.readAllBytes(f.toPath());if(all.length<32)return null;byte[] bytes=Arrays.copyOf(all,all.length-32);if(!Arrays.equals(hash(bytes),Arrays.copyOfRange(all,all.length-32,all.length)))return null;
        DataInputStream in=new DataInputStream(new ByteArrayInputStream(bytes));if(in.readInt()!=1)return null;ChunkSurface c=new ChunkSurface(in.readInt(),in.readInt(),in.readInt());if(c.dimension<0||c.dimension>1)return null;
        for(int i=0;i<256;i++){c.ids[i]=in.readInt();c.heights[i]=in.readInt();if(c.ids[i]<0||c.ids[i]>4095||c.heights[i]<-1||c.heights[i]>255)return null;}c.pointsLimited=in.readBoolean();int n=in.readInt();if(n<0||n>4096)return null;
        for(int i=0;i<n;i++){MapPoint p=new MapPoint(in.readInt(),in.readInt(),in.readInt(),c.dimension,in.readInt(),in.readUTF());p.readable=in.readBoolean();p.text=in.readUTF();p.issue=in.readUTF();int count=in.readInt();if(count<0||count>27)return null;List<PlayerReader.Item> items=new ArrayList<>();for(int j=0;j<count;j++){int slot=in.readInt(),id=in.readInt(),q=in.readInt(),dur=in.readInt(),effects=in.readInt();if(effects<0||effects>128||q<1)return null;Map<Integer,Integer> enchantments=new TreeMap<>();for(int k=0;k<effects;k++)enchantments.put(in.readInt(),in.readInt());items.add(new PlayerReader.Item(slot,id,q,dur==-1?null:dur,enchantments));}p.items=Collections.unmodifiableList(items);c.points.add(p);}if(in.available()!=0)return null;hits++;f.setLastModified(System.currentTimeMillis());return c;
    }catch(Exception e){return null;}}
    static synchronized void write(String key,ChunkSurface c){if(root==null)return;File temp=null;try{ByteArrayOutputStream bytes=new ByteArrayOutputStream();DataOutputStream out=new DataOutputStream(bytes);out.writeInt(1);out.writeInt(c.x);out.writeInt(c.z);out.writeInt(c.dimension);for(int i=0;i<256;i++){out.writeInt(c.ids[i]);out.writeInt(c.heights[i]);}out.writeBoolean(c.pointsLimited);out.writeInt(c.points.size());for(MapPoint p:c.points){out.writeInt(p.x);out.writeInt(p.y);out.writeInt(p.z);out.writeInt(p.blockId);out.writeUTF(p.kind);out.writeBoolean(p.readable);out.writeUTF(p.text);out.writeUTF(p.issue);out.writeInt(p.items.size());for(PlayerReader.Item i:p.items){out.writeInt(i.slot);out.writeInt(i.id);out.writeInt(i.quantity);out.writeInt(i.durability==null?-1:i.durability);out.writeInt(i.enchantments.size());for(Map.Entry<Integer,Integer> e:i.enchantments.entrySet()){out.writeInt(e.getKey());out.writeInt(e.getValue());}}}byte[] data=bytes.toByteArray();if(data.length+32>MAX)return;temp=File.createTempFile("cache-",".tmp",root);try(OutputStream file=new FileOutputStream(temp)){file.write(data);file.write(hash(data));}Files.move(temp.toPath(),new File(root,key(key)).toPath(),StandardCopyOption.REPLACE_EXISTING);trim();}catch(IOException ignored){}finally{if(temp!=null)temp.delete();}}
    private static void trim(){File[] files=root.listFiles();if(files==null)return;long size=0;for(File f:files)size+=f.length();Arrays.sort(files,Comparator.comparingLong(File::lastModified));for(File f:files){if(size<=128L*1024*1024)break;long n=f.length();if(f.delete())size-=n;}}
    public static void clear(){synchronized(TerrainDiskCache.class){if(root!=null){File[] files=root.listFiles();if(files!=null)for(File f:files)if(f.isFile())f.delete();}hits=0;}SurfaceDecodeCache.clear();}
}
