package io.github.realmcraft.companion;
import org.json.*;
import java.util.*;
/** Strict bounded transfer schema; validates all entries before any preferences are changed. */
final class NotebookTransfer {
    static JSONObject validate(String data,String world,String seed)throws JSONException{
        if(data.length()>1024*1024)throw new JSONException("Transfer too large");JSONObject root=new JSONObject(data);if(root.getInt("format")!=1||!root.getString("world").equals(world)||!root.getString("seed").equals(seed))throw new JSONException("Different world or unsupported format / Andere Welt oder unbekanntes Format");
        for(String key:new String[]{"markers","bookmarks","packing","projects"}){JSONArray rows=root.getJSONArray(key);int max=key.equals("markers")?200:key.equals("bookmarks")?30:key.equals("projects")?20:100;if(rows.length()>max)throw new JSONException("Too many entries");Set<String> ids=new HashSet<>();for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);if(!ids.add(row.getString("id")))throw new JSONException("Duplicate entry");if(key.equals("packing")){target(row);continue;}if(!row.getString("id").matches("[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}"))throw new JSONException("Invalid ID");String name=row.getString("name");if(name.trim().isEmpty()||name.length()>80)throw new JSONException("Invalid name");if(key.equals("projects")){JSONArray items=row.getJSONArray("items");if(items.length()>100)throw new JSONException("Too many materials");Set<Integer> materialIds=new HashSet<>();for(int j=0;j<items.length();j++){target(items.getJSONObject(j));if(!materialIds.add(items.getJSONObject(j).getInt("item")))throw new JSONException("Duplicate material");}continue;}
            int dimension=row.getInt(key.equals("markers")?"d":"dimension");if(dimension<0||dimension>1)throw new JSONException("Invalid dimension");for(String axis:new String[]{"x","z"}){double n=row.getDouble(axis);if(!Double.isFinite(n)||n<Integer.MIN_VALUE||n>Integer.MAX_VALUE)throw new JSONException("Invalid coordinate");}
            if(key.equals("markers")){row.getInt("y");row.getBoolean("favorite");}else{double zoom=row.getDouble("zoom");if(!Double.isFinite(zoom)||zoom<.00000001||zoom>100000)throw new JSONException("Invalid zoom");int h=row.getInt("ceiling"),count=row.getInt("chunks"),radius=row.getInt("radius");if(h<0||h>255||count<1||count>16384||radius<0||radius>4096)throw new JSONException("Invalid render settings");row.getInt("centerX");row.getInt("centerZ");row.getBoolean("slice");row.getBoolean("textures");if(!Arrays.asList("all","sign","chest","bed","crafting").contains(row.getString("filter")))throw new JSONException("Invalid filter");}}
        }return root;
    }
    private static void target(JSONObject row)throws JSONException{int item=row.getInt("item");long needed=row.getLong("needed");if(item<1||item>65535||needed<1||needed>1000000||!row.getString("id").equals(Integer.toString(item)))throw new JSONException("Invalid packing target");}
}
